### ISSUE TITLE
Simple Authorization Issues

### ISSUE THREAD

**Issue by rh-dford** [SystemCraftsman/strimzi-kafka-cli#97]
I am using the tutorials and following the TLS AUth using CLI and Simple ACL Authorization using CLI. 
CLI Version: 0.1.0a59
Strimzi Version: 0.25.0
Kubectl Version: v1.22.0

I set up the cluster with CLI :kfk clusters --create --cluster my-cluster -n kafka
I set up the topic: kfk topics --create --topic my-topic --partitions 12 --replication-factor 3 -n kafka -c my-cluster
I run console consumer and producer and messages work. 

I then alter to add the authorization:  kfk clusters --alter --cluster my-cluster -n kafka
![image](https://user-images.githubusercontent.com/54030849/147241169-adba2cfd-77af-4008-8532-4363165bcbd1.png)

I then run the console producer and get the failed authentication error. 

I create an user - my-user kfk users --create --user my-user --authentication-type tls -n kafka -c my-cluster

Then I run the get_keys.sh script to create the  two files trustore.jks and user.p12 
I create the client config file:
![image](https://user-images.githubusercontent.com/54030849/147241570-2c0cdb5f-f565-49f3-a252-7130c56dc2ea.png)

I then run the producer and consumer including client.properties file: kfk console-producer --topic my-topic -n kafka -c my-cluster --producer.config client.properties

Messages flow fine. 

I then alter the kafka cluster to include authorization type: simple 

I then try to run the producer and get the expected errors 

I then alter the user: 
kfk users --alter --user my-user --authorization-type simple --add-acl --resource-type topic --resource-name my-topic -n kafka -c my-cluster

I get the following warning:

> Warning: resource kafkausers/my-user is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.

Looking at the user via kfk users --describe --user my-user -n kafka -c my-cluster -o yaml

![image](https://user-images.githubusercontent.com/54030849/147244010-d1fe7a0f-8ebc-415b-9137-bc888b53ee25.png)

I can see the ACL included. 

I then start the producer:  kfk console-producer --topic my-topic -n kafka -c my-cluster --producer.config client.properties
and when I send a message on the CLI : 
![image](https://user-images.githubusercontent.com/54030849/147244283-df404807-68a8-4891-9bdd-31d806885b7b.png)

When I look at the logs in the kafka cluster pod I see: 

> INFO Principal = User:ANONYMOUS is Denied Operation = Describe from host = 10.129.2.39 on resource = Topic:LITERAL:my-topic for request = Metadata with resourceRefCount = 1 (kafka.authorizer.logger) [data-plane-kafka-request-handler-7]

So why does my console producer and consumer get authorized but in the authorization the user is ANONYMOUS?

**Comment by rh-dford** [comment]
Not sure if this matters but looking at the services created there is a port 9091 but I don't have a listener defined for it. 
![image](https://user-images.githubusercontent.com/54030849/147256304-f4562b3c-9bc5-4ad8-9f97-c52bd548981b.png)

**Comment by dford-acc** [comment]
Today I spun up a new openshift cluster in OpenTLC and ran through the AuthN and AuthZ demos and had the same experience

**Comment by rh-dford** [comment]
Today I spun up a new openshift cluster in OpenTLC and ran through the AuthN and AuthZ demos and had the same experience

**Comment by mabulgu** [comment]
> Today I spun up a new openshift cluster in OpenTLC and ran through the AuthN and AuthZ demos and had the same experience

Thanks Dave. Are those the same versions of amq streams btw? What are the exact versions for both clusters.

**Comment by dford-acc** [comment]
The client's version is 1.8.2 of AMQ streams. I already shut down the OpenTLC one so I didn't see what exact version 1.8.X? 
Do you want me to spin up another cluster to get the version? If you wanted to test it out you could spin up an OpenTLC or RHPDS cluster

**Comment by rh-dford** [comment]
The client's version is 1.8.2 of AMQ streams. I already shut down the OpenTLC one so I didn't see what exact version 1.8.X?
Do you want me to spin up another cluster to get the version? If you wanted to test it out you could spin up an OpenTLC or RHPDS cluster

**Comment by mabulgu** [comment]
I guess this had been an issue with the relevant version. I tried out and saw no issues. Sorry for the latency in the response; I am the only contributor for now so🤷‍♂️
